micronaut:
  application:
    name: landlordAppBackend
  server:
    port: 8091
    context-path: /api
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 10
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
