micronaut:
  application:
    name: landlordAppBackend
  server:
    port: 8091
    context-path: /api
  security:
    ip-patterns:
      - "0.0.0.0"
    authentication: bearer
    token.jwt.signatures.secret.generator.secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 10
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
landlord.app:
  hash.key: ${HASH_KEY}