micronaut:
  application:
    name: landlordAppBackend
  server:
    port: 8091
    context-path: /api
  security:
    authentication: bearer
    token.jwt.signatures.secret.generator:
      secret: ${JWT_GENERATOR_SIGNATURE_SECRET}
      base64: true
      jws-algorithm: HS384
    token:
      jwt:
        claims-validators:
          issuer: landlord-app-backend
  serde:
    date-format: "yyyy-MM-dd"
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    driverClassName: org.postgresql.Driver
    maximum-pool-size: 10
jooq:
  datasources:
    default:
      sql-dialect: 'POSTGRES'
landlord.app:
  hash.key: ${HASH_KEY}
  api.key: ${API_KEY}
logger.levels:
  root: INFO
  io.micronaut.security.rules: DEBUG