micronaut:
  server:
    port: ${PORT}
  security:
    ip-patterns:
      - 86.88.150.144
      - 2a02:a44a:4af2:1:4c05:fde3:d799:7c3b
datasources:
  default:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PWD}
